#include "../instr/compute.h"
#include "../instr/ldst.h"
#include "../instr/special.h"
#include "../instr/jump.h"
#include "../instr/branch.h"
#include "../instr/set.h"
#include "../instr/csr.h"
#include "../instr/trap.h"